id: P004164
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W3CN4038
  title: བཀའ་བརྒྱུད་པའི་རྒྱུན་འདོན་ཕྱོགས་བསྒྲིགས།
  author: ''
  volumes:
    e6fcfe6aaae4415c8910d4ad99b7e96d:
      image_group_id: I3CN4221
      title: ''
      volume_number: 1
      total_pages: 230
      base_file: v001.txt
